# This code sources all the functions needed for performing the factor analysis.
source("R/readUseful.R")
source("R/saveAllUseful.R")
source("R/createOrgMega.R")
source("R/createACSmat.R")
source("R/transform_vars.R")
source("R/modelComp.R")
source("R/factorAnalysis.R")
source("R/factorName.R")
source("R/fa_bootstrap.R")
source("R/plotLoads.R")
source("R/myCFA.R")
source("R/fCorrplot.R")
source("R/MentalHealthCorr.R")